In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [5]:
arr3d = np.random.random((3,3,3))
arr3d

array([[[7.38947256e-01, 4.81716229e-01, 2.48957188e-01],
        [3.79313750e-01, 2.31615143e-01, 7.89292856e-01],
        [4.11687612e-01, 9.76965948e-01, 7.18421667e-02]],

       [[6.96954832e-01, 7.10105595e-01, 4.25803238e-01],
        [1.12371742e-01, 1.75477659e-01, 6.41708224e-01],
        [6.57064418e-01, 7.80069514e-01, 7.87590032e-01]],

       [[7.17530303e-01, 7.78713860e-01, 5.91083379e-01],
        [9.59847420e-01, 9.49945867e-01, 6.07675375e-01],
        [5.44138374e-04, 6.74150853e-01, 2.09124797e-01]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [49]:
a = np.diag(1+np.arange(4) , k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [53]:
cp = np.zeros((8,8),dtype='int')
cp[1::2 , ::2] = 1
cp[::2 , 1::2] = 1
print(cp)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [59]:
nrm = np.random.random((5,5))
nrmMax , nrmMin = np.max(nrm) , np.min(nrm)
nrm = (nrm-nrmMin)/(nrmMax - nrmMin)
print(nrm)

[[0.         0.26226295 0.29653696 0.56327354 0.11754001]
 [0.11566648 0.4374855  0.21914421 0.36239651 0.61215749]
 [1.         0.50821204 0.38512303 0.2717471  0.80106331]
 [0.16764465 0.44068411 0.9885911  0.7109002  0.51063022]
 [0.07615299 0.66389519 0.98363566 0.37455843 0.7000429 ]]


# 5.  How to find common values between two arrays?

In [19]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays : ",np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays :  [10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [66]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yesterday : ",yesterday)
today = np.datetime64('today','D')
print("Today : ",today)
tomarrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("Tomarrow : ",tomarrow)

Yesterday :  2020-07-25
Today :  2020-07-26
Tomarrow :  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [79]:
A = np.random.randint(4,20,5)
B = np.random.randint(4,20,5)
print(A)
print(B)
print(np.allclose(A,B))

[8 9 5 5 7]
[ 8 16  4 18  9]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [87]:
rv = np.random.random(10)
rv[rv.argmax()] = 0
print(rv)

[0.39719956 0.29036909 0.22674372 0.09452079 0.02040792 0.58591253
 0.         0.34777598 0.26299694 0.61641689]


# 9. How to print all the values of an array?

In [100]:

allValue = np.zeros((25,25))
print(allValue)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [105]:
arr = np.random.random((5,10))
arr1 = arr - arr.mean(axis =1 , keepdims =True)
print(arr)
print()
print(arr1)

[[0.06389163 0.51692848 0.64893234 0.16321499 0.81945846 0.6557082
  0.27170698 0.59231359 0.82283596 0.00956767]
 [0.0715495  0.77046485 0.80794651 0.71371724 0.24070102 0.33137041
  0.99950199 0.66244777 0.03993036 0.66274318]
 [0.27750163 0.33131928 0.73642833 0.39849009 0.38238797 0.67236585
  0.10015861 0.11559178 0.36838819 0.14158878]
 [0.98059258 0.61680745 0.39753672 0.60801329 0.16585517 0.84854505
  0.84257651 0.21768957 0.17918837 0.76373355]
 [0.84870849 0.7578958  0.7396036  0.00134846 0.56560871 0.77222385
  0.14462198 0.95446144 0.08131552 0.09855326]]

[[-0.3925642   0.06047265  0.19247652 -0.29324084  0.36300263  0.19925237
  -0.18474885  0.13585776  0.36638013 -0.44688816]
 [-0.45848778  0.24042757  0.27790923  0.18367996 -0.28933626 -0.19866687
   0.46946471  0.13241049 -0.49010693  0.1327059 ]
 [-0.07492042 -0.02110277  0.38400628  0.04606804  0.02996592  0.3199438
  -0.25226344 -0.23683027  0.01596614 -0.21083327]
 [ 0.41853875  0.05475363 -0.16451711  0.04595946 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [2]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 5. 3. 2. 5. 3. 1. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [5]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

dotp = np.diag(np.dot(A, B))
print(dotp)


[ 30  66 147]


# 13.How to find the most frequent value in an array?

In [9]:
most_freq = np.random.randint(0,10,50)
print (most_freq)
print('Rank:', np.bincount(most_freq).argmax())

[7 0 8 4 3 1 1 7 5 5 0 1 9 8 1 3 0 4 8 5 6 6 1 9 1 1 4 8 3 9 4 9 9 9 8 4 5
 9 9 0 2 6 9 0 2 8 5 6 0 2]
Rank: 9


# 14.How to get the n largest values of an array

In [10]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9997 9999 9996 9998]


# 15.How to create a record array from a regular array?

In [16]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Z)
print()
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
